projects:
  vouchedbyme:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/api.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
